name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: JesseDMoore1994/gh-pages-pelican-action@shell-init-scripts
      env:
        PELICAN_THEME_FOLDER: ./Flex
        USER_DEFINED_INIT_SCRIPT: ./initialize.sh
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
